services:
  agent:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=ollama
      # Fixes some npx interactions in containers
      - FORCE_COLOR=1
    tty: true

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_backend
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # Uncomment below to use your NVIDIA GPU
    # deploy:
    # resources:
    # reservations:
    # devices:
    # - driver: nvidia
    # count: 1
    # capabilities: [gpu]
    restart: always

volumes:
  ollama_data:
